name: Create AWS Infra
on: 
    workflow_dispatch:
run-name: Create aws infra
jobs: 
    run-data:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps: 
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Configure AWS Credentials with OIDC
              uses: aws-actions/configure-aws-credentials@v4.3.1
              with:
                    aws-region: us-east-1
                    role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
            - name: Build Docker Image
              run: docker build -t my-lambda-image .
            - name: Check Python
              run: docker run --rm --entrypoint python my-lambda-image --version
            - name: Create ECR repo
              run: |
                aws ecr delete-repository --repository-name my-lambda-repo --force
                aws ecr create-repository --repository-name my-lambda-repo --region="us-east-1"
            - name: Push image to ECR
              run: |
                aws ecr get-login-password --region "us-east-1" | docker login --username AWS --password-stdin 483151609062.dkr.ecr.us-east-1.amazonaws.com
                docker tag my-lambda-image:latest 483151609062.dkr.ecr.us-east-1.amazonaws.com/my-lambda-repo:latest
                docker push 483151609062.dkr.ecr.us-east-1.amazonaws.com/my-lambda-repo:latest
            - name: Configure terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.10.1"
            - name: Create infra
              run: | 
                cd iac
                terraform init
                terraform apply --auto-approve
