name: Destroy AWS Infra
on: 
    workflow_dispatch:
run-name: Destroy aws infra
jobs: 
    run-data:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps: 
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Configure AWS Credentials with OIDC
              uses: aws-actions/configure-aws-credentials@v4.3.1
              with:
                    aws-region: us-east-1
                    role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
            - name: Configure terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.10.1"
            - name: Destroy infra
              run: | 
                cd iac
                terraform init
                terraform destroy --auto-approve
