name: Create AWS Infra
on: 
    push:
run-name: Create aws infra
jobs: 
    run-data:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps: 
            - name: Show val
              run: echo "hello there"
            - name: Configure AWS Credentials with OIDC
              uses: aws-actions/configure-aws-credentials@v4.3.1
              with:
                    aws-region: us-east-1
                    role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
            - name: List s3 buckets
              run: aws s3 ls